# Generated by Django 4.2.1 on 2023-05-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BetterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_long_link_proto', models.CharField(choices=[('h', 'HTTP'), ('s', 'HTTPS')], default='h', max_length=1)),
                ('old_link_url', models.CharField(max_length=255)),
                ('short_link', models.CharField(max_length=64, unique=True)),
            ],
        ),
    ]
